# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('sold', models.BooleanField(default=False)),
                ('recycle', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_code', models.CharField(max_length=10)),
                ('matric_no', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=4)),
                ('mobile', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('qty_in', models.IntegerField()),
                ('qty_sold', models.IntegerField()),
                ('qty_left', models.IntegerField()),
                ('earnings', models.IntegerField()),
                ('settled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='clothes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Seller'),
        ),
    ]
