# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.AlterField(
            model_name='seller',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='qty_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='qty_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='qty_sold',
            field=models.IntegerField(default=0),
        ),
    ]
