# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170226_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
